apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  activeDeadlineSeconds: 15
  backoffLimit: 2
  completions: 4
  parallelism: 2
  template:
    spec:
      containers:
      - image: busybox
        name: echo-job
        imagePullPolicy: IfNotPresent
        command: 
          - sh 
          - -c
          - sleep $(($RANDOM % 10 + 1)) && echo done
        args: ["hello","world!"]
      restartPolicy: OnFailure
