apiVersion: v1
metadata: 
  name: mariadb-cm
kind: ConfigMap

data:
  DATABASE: 'db'
  USER: 'wp'
  PASSWORD: '123'
  ROOT_PASSWORD: '123'
--- 
apiVersion: v1
kind: Pod
metadata: 
  name: mariadb-cm-pod
  labels:
    app: wordpress
    role: database
spec:
  containers:
    - image: mariadb:10
      name: mariadb10
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
      envFrom:
        - prefix: 'MARIADB_'
          configMapRef: 
           name: mariadb-cm
