apiVersion: v1
metadata: 
  name: mariadb-secret
kind: Secret

data:
  DATABASE: 'ZGI='
  USER: 'd3A='
  PASSWORD: 'MTIz'
  ROOT_PASSWORD: 'MTIz'
--- 
apiVersion: v1
kind: Pod
metadata: 
  name: mariadb-secret-pod
  labels:
    app: wordpress
    role: database
spec:
  containers:
    - image: mariadb:10
      name: mariadb10
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
      envFrom:
        - prefix: 'MARIADB_'
          secretRef: 
           name: mariadb-secret
