apiVersion: v1
kind: ConfigMap
metadata: 
  name: wp-cm

data:
  HOST: '172.17.0.8'
  USER: 'wp'
  PASSWORD: '123'
  NAME: 'db'
--- 
apiVersion: v1
kind: Pod
metadata: 
  name: wp-cm-pod
  labels:
    app: wordpress
    role: website
spec:
  containers:
    - image: wordpress:5
      name: wordpress5
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80
      envFrom: 
        - prefix: 'WORDPRESS_DB_'
          configMapRef:
            name: wp-cm
