apiVersion: v1
kind: Secret
metadata: 
  name: wp-secret

data:
  HOST: 'MTcyLjE3LjAuMg=='
  USER: 'd3A='
  PASSWORD: 'MTIz'
  NAME: 'ZGI='
--- 
apiVersion: v1
kind: Pod
metadata: 
  name: wp-secret-pod
  labels:
    app: wordpress
    role: website
spec:
  containers:
    - image: wordpress:5
      name: wordpress5-sc
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80
      envFrom: 
        - prefix: 'WORDPRESS_DB_'
          secretRef:
            name: wp-secret
