
apiVersion: v1
kind: Pod
metadata: 
  name: ngx-pod
  labels: 
    env: demo
    owner: yangxin 

spec: 
  containers: 
    - image: nginx:alpine
      name: ngx
      ports:
        - containerPort: 80

